# Analyzing Patient Data

Objectives:
- Explain what a library is and what libraries are used for
- Import a Python library and use the functions it contains
- Read tabular data from a file into a program
- Select individual values and subsections from data
- Perform operations on arrays of data

## Loading data into Python

Libraries in Python:
- Libraries are like lab equipment - they provide additional functionality to basic Python
- Import only what you need to keep programs efficient
- NumPy (Numerical Python) is used for working with arrays and matrices



In [3]:
import numpy

Importing NumPy:
- Use `import numpy` to access the library
- Dot notation: `numpy.function()` - the function belongs to the numpy library

Loading Data:
- Use `numpy.loadtxt()` to read data from files
- Parameters: `fname` (filename) and `delimiter` (separator between values)
- Assign data to a variable to store it in memory: `data = numpy.loadtxt(...)`

In [4]:
data=numpy.loadtxt("data/inflammation-01.csv",delimiter=",");

In [5]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]], shape=(60, 40))

Understanding Arrays:
- NumPy creates N-dimensional arrays (ndarray)
- Arrays contain elements of the same type
- Use `type()` to check the object type
- Use `.dtype` to check the data type inside the array
- Use `.shape` to see array dimensions (rows, columns)

![](https://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.svg)

In [6]:
data.dtype

dtype('float64')

In [7]:
data.shape

(60, 40)

In [8]:
type(data)

numpy.ndarray

Indexing:
- Python uses zero-based indexing (starts counting from 0)
- Access elements using `array[row, column]`
- Example: `data[0, 0]` is the first element
- Index `[0, 0]` appears in upper left corner (not lower left like Cartesian coordinates)

In [9]:
print(data[1,1])

1.0


## Slicing data

**Slicing Arrays:**
- Select sections of arrays using slice notation: `start:end`
- The slice goes up to, but **not including**, the end index
- Example: `data[0:4, 0:10]` selects rows 0-3 and columns 0-9



In [10]:
data[0:4,0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

**Slice Boundaries:**
- Don't have to start at 0: `data[5:10, 0:10]`
- Can omit lower bound (defaults to 0): `data[:3, 36:]`
- Can omit upper bound (goes to the end): `data[5:, :]`
- Using `:` alone selects everything along that axis



In [11]:
data[5:10, 0:10]

array([[0., 0., 1., 2., 2., 4., 2., 1., 6., 4.],
       [0., 0., 2., 2., 4., 2., 2., 5., 5., 8.],
       [0., 0., 1., 2., 3., 1., 2., 3., 5., 3.],
       [0., 0., 0., 3., 1., 5., 6., 5., 5., 8.],
       [0., 1., 1., 2., 1., 3., 5., 3., 5., 8.]])

**Rules to Remember:**
- The difference between upper and lower bounds = number of values in the slice
- Slicing works on strings too: `element[0:3]` for first 3 characters
- Slices can use negative indices to count from the end

## Analyzing data

**Statistical Functions:**
- NumPy provides functions for statistical analysis
- `numpy.mean(array)` - calculate average
- `numpy.amax(array)` - find maximum value
- `numpy.amin(array)` - find minimum value
- `numpy.std(array)` - calculate standard deviation


In [12]:
numpy.mean(data)

np.float64(6.14875)

In [13]:
numpy.amax(data)

np.float64(20.0)

In [14]:
numpy.amin(data)

np.float64(0.0)

In [15]:
numpy.std(data)

np.float64(4.613833197118566)

**Operating Along Axes:**
- Can apply functions across specific axes in multi-dimensional arrays
- `axis=0` - operates down rows (column-wise)
- `axis=1` - operates across columns (row-wise)
- Example: `numpy.mean(data, axis=0)` gives average for each day across all patients
- Example: `numpy.amax(data, axis=1)` gives maximum for each patient across all days

In [16]:
numpy.mean(data, axis=0)

array([ 0.        ,  0.45      ,  1.11666667,  1.75      ,  2.43333333,
        3.15      ,  3.8       ,  3.88333333,  5.23333333,  5.51666667,
        5.95      ,  5.9       ,  8.35      ,  7.73333333,  8.36666667,
        9.5       ,  9.58333333, 10.63333333, 11.56666667, 12.35      ,
       13.25      , 11.96666667, 11.03333333, 10.16666667, 10.        ,
        8.66666667,  9.15      ,  7.25      ,  7.33333333,  6.58333333,
        6.06666667,  5.95      ,  5.11666667,  3.6       ,  3.3       ,
        3.56666667,  2.48333333,  1.5       ,  1.13333333,  0.56666667])

In [17]:
numpy.amax(data, axis=1)

array([18., 18., 19., 17., 17., 18., 17., 20., 17., 18., 18., 18., 17.,
       16., 17., 18., 19., 19., 17., 19., 19., 16., 17., 15., 17., 17.,
       18., 17., 20., 17., 16., 19., 15., 15., 19., 17., 16., 17., 19.,
       16., 18., 19., 16., 19., 18., 16., 19., 15., 16., 18., 14., 20.,
       17., 15., 17., 16., 17., 19., 18., 18.])

**Tips:**
- Use tab completion in Jupyter/IPython to explore available functions
- Add `?` after a function name to see documentation: `numpy.mean?`
- Multiple assignment lets you assign several values at once
- Array operations can work on selected rows/columns: `numpy.amax(data[0, :])`